# version of the syntax used in this file
version: '3.9'

services:
  web:
    # path of dockerfile
    build: .
    # username/imagename
    image: "phpdockenv/softdesk"
    command: "python manage.py runserver 0.0.0.0:8000"
    # expose:
    #  -8000
    ports:
      - 8000:8000
