# version of the syntax used in this file
version: '3.9'

# here we build / .ci = use cache to save time

services:
  web:
    # path of dockerfile
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "phpdockenv/softdesk"
    # username/imagename
    image: "phpdockenv/softdesk"
    command: "python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    env_file: # Add environnement variables
      - ./.env 

  nginx:
    # path of dockerfile in file nginx
    build:
      context: ./nginx
      cache_from:
        - "phpdockenv/nginx"
    # naming image
    image: "phpdockenv/nginx"
    ports:
      - 80:80
    env_file: # Add environnement variables
      - ./.env
    
    depends_on:
      - web