# version of the syntax used in this file
version: '3.9'

services:
  web:
    # path of Dockerfile
    build: .
    # username/imagename
    image: "phpdockenv/softdesk"
    command: "python manage.py runserver 0.0.0.0:8000"
    # expose:
    #   - 8000
    ports:
        # internal:external
      - 8000:8000
    env_file: # Add environnement variables
      - ./.env
    
  # lunch project port 80
  nginx:
    # path of dockerfile in file nginx
    build: ./nginx
    # naming image
    image: "phpdockenv/nginx"
    ports:
      - 80:80
    env_file: # Add environnement variables
      - ./.env
    depends_on:
      - web