name: ci-cd 

on:
  push:

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  WEB_IMAGE: ${{ secrets.WEB_IMAGE }}
  NGINX_IMAGE: ${{ secrets.NGINX_IMAGE }}

jobs:
  linting: # quality code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install flake8
      - run: pip install setuptools>=65.5.1 wheel>=0.38.1
      - run: pip install -r requirements.txt
      - run: flake8 .
  
  test-coverage: #Test and coverage (min 80%)
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install setuptools>=65.5.1 wheel>=0.38.1
      - run: pip install -r requirements.txt
      - run: pip install coverage
      - name: coverage test and report
        run: |
            coverage erase
            coverage run manage.py test
            coverage report

  build-and-push: # build docker image and push docker hub
    runs-on: ubuntu-latest
    needs: test-coverage
    steps:
      - uses: actions/checkout@v3
      - name: login to dockerhub
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      - name: pull web and nginx image from docker hub # Get last image(s)
        # || = or (avoid crash but goahead)
        run: |
            docker pull $WEB_IMAGE || true 
            docker pull $NGINX_IMAGE || true
      - name: build docker image
        run: docker-compose -f docker-compose.ci.yml build
      - name:
        run: |
            docker push $WEB_IMAGE 
            docker push $NGINX_IMAGE
            